# Main training script for now

## Train number 1

Logging results to runs/classify/train

train: 23 images in 3 classes

val: 6 images in 3 classes



In [3]:
from ultralytics.models.yolo.classify.train import ClassificationTrainer

args = {
    # Train Setting
    'model':'yolov8n-cls.pt', 
    'data':'/root/aifr/bottle-classification-YOLOv8/data', 
    'epochs':500,
    'batch':1,
    'scale':0,
    # 'cache':True,

    # Augmentation
    'erasing':0,    
}

trainer = ClassificationTrainer(overrides=args)
trainer.train()

Ultralytics YOLOv8.2.6 🚀 Python-3.8.10 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2070 SUPER, 8192MiB)
engine/trainer: task=classify, mode=train, model=yolov8n-cls.pt, data=/root/aifr/bottle-classification-YOLOv8/data, epochs=500, time=None, patience=100, batch=1, imgsz=224, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=Fals

train: Scanning /root/aifr/bottle-classification-YOLOv8/data/train... 23 images, 0 corrupt: 100%|██████████| 23/23 [00:00<?, ?it/s]
val: Scanning /root/aifr/bottle-classification-YOLOv8/data/val... 6 images, 0 corrupt: 100%|██████████| 6/6 [00:00<?, ?it/s]


optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 8 dataloader workers
Logging results to runs/classify/train
Starting training for 500 epochs...

      Epoch    GPU_mem       loss  Instances       Size


      1/500     0.508G      1.113          1        224: 100%|██████████| 23/23 [00:03<00:00,  5.78it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.91it/s]

                   all      0.333          1



      Epoch    GPU_mem       loss  Instances       Size


      2/500     0.367G      1.075          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.66it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.73it/s]

                   all      0.333          1



      Epoch    GPU_mem       loss  Instances       Size


      3/500     0.367G      1.099          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.15it/s]

                   all      0.833          1



      Epoch    GPU_mem       loss  Instances       Size


      4/500     0.367G      1.038          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.05it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.17it/s]


                   all      0.833          1

      Epoch    GPU_mem       loss  Instances       Size


      5/500     0.367G      1.063          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.13it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.48it/s]

                   all      0.833          1



      Epoch    GPU_mem       loss  Instances       Size


      6/500     0.367G      1.056          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.06it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.20it/s]

                   all        0.5          1



      Epoch    GPU_mem       loss  Instances       Size


      7/500     0.367G      1.002          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.52it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.75it/s]

                   all        0.5          1



      Epoch    GPU_mem       loss  Instances       Size


      8/500     0.367G      1.028          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.87it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.42it/s]

                   all        0.5          1



      Epoch    GPU_mem       loss  Instances       Size


      9/500     0.367G      1.012          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.00it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.75it/s]

                   all        0.5          1



      Epoch    GPU_mem       loss  Instances       Size


     10/500     0.367G      1.001          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 21.83it/s]


                   all        0.5          1

      Epoch    GPU_mem       loss  Instances       Size


     11/500     0.367G     0.9829          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.43it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 22.06it/s]

                   all      0.667          1



      Epoch    GPU_mem       loss  Instances       Size


     12/500     0.367G     0.9588          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.36it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.40it/s]

                   all      0.667          1



      Epoch    GPU_mem       loss  Instances       Size


     13/500     0.367G     0.9242          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.65it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.79it/s]

                   all      0.667          1



      Epoch    GPU_mem       loss  Instances       Size


     14/500     0.367G     0.9498          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.17it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.80it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


     15/500     0.367G      0.896          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.93it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.20it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     16/500     0.367G     0.8936          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.49it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.72it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     17/500     0.367G     0.8579          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.08it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.34it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     18/500     0.367G     0.8378          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.68it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.90it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     19/500     0.367G     0.8179          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.74it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 48.19it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     20/500     0.367G     0.8434          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.90it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     21/500     0.367G     0.7937          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.10it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.49it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     22/500     0.367G     0.7596          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.79it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.00it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     23/500     0.367G     0.7682          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.64it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.98it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     24/500     0.367G     0.7758          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.51it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.50it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     25/500     0.367G     0.7715          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.47it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.79it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     26/500     0.367G     0.7246          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.82it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


     27/500     0.367G     0.7571          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.47it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.47it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     28/500     0.367G     0.7554          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.87it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.48it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     29/500     0.367G     0.6575          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.66it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     30/500     0.367G        0.7          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.92it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.47it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     31/500     0.367G      0.642          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.71it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     32/500     0.367G       0.57          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.04it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.89it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


     33/500     0.367G      0.614          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.42it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 21.50it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     34/500     0.367G     0.6275          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.62it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.49it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     35/500     0.367G     0.5776          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.83it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.02it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     36/500     0.367G     0.5319          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.16it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     37/500     0.367G     0.5038          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.83it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.71it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     38/500     0.367G     0.5369          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.27it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.21it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     39/500     0.367G     0.4876          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.42it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.88it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


     40/500     0.367G      0.494          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.81it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.81it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


     41/500     0.367G     0.5107          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.40it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.42it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     42/500     0.367G     0.4086          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.67it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     43/500     0.367G     0.3876          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.99it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.66it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     44/500     0.367G     0.4578          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.63it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.24it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     45/500     0.367G     0.3734          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.80it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.68it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     46/500     0.367G     0.3053          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.26it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.73it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


     47/500     0.367G     0.3264          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.96it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 23.87it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     48/500     0.367G     0.2812          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.59it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.57it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     49/500     0.367G     0.3134          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.66it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.51it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     50/500     0.367G      0.264          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.44it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.26it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     51/500     0.367G     0.2816          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.61it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.09it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     52/500     0.367G     0.2259          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.02it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.90it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     53/500     0.367G     0.2695          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.93it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.47it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     54/500     0.367G     0.1806          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.43it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.20it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     55/500     0.367G      0.194          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.22it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.07it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     56/500     0.367G     0.1791          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.41it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     57/500     0.367G     0.1581          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.70it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.68it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     58/500     0.367G     0.1787          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.77it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     59/500     0.367G     0.1424          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.53it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 29.05it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     60/500     0.367G     0.1061          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.27it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.42it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     61/500     0.367G     0.1215          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.45it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.04it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     62/500     0.367G     0.1248          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.72it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     63/500     0.367G       0.11          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.93it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     64/500     0.367G     0.1071          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.14it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     65/500     0.367G    0.08744          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.59it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.82it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     66/500     0.367G    0.07723          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.19it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.33it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     67/500     0.367G    0.07291          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.59it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.35it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     68/500     0.367G    0.06923          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.39it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     69/500     0.367G    0.05293          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.33it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.88it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     70/500     0.367G    0.07854          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.99it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 18.94it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     71/500     0.367G    0.05136          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.80it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.15it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     72/500     0.367G    0.05217          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 43.04it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     73/500     0.367G    0.03822          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.18it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.46it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     74/500     0.367G    0.04644          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.92it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     75/500     0.367G    0.04849          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.99it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.34it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     76/500     0.367G     0.0481          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.68it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.18it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     77/500     0.367G    0.04004          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.26it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.06it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     78/500     0.367G    0.05096          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.79it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.76it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     79/500     0.367G    0.02321          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.16it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


     80/500     0.367G    0.02042          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.19it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     81/500     0.367G    0.02943          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.49it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     82/500     0.367G    0.02314          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.73it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.71it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     83/500     0.367G    0.01666          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.47it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 19.39it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     84/500     0.367G    0.01778          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.57it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.51it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


     85/500     0.367G    0.01856          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.80it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.70it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     86/500     0.367G    0.01602          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.40it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.56it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     87/500     0.367G    0.01296          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.69it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     88/500     0.367G     0.0135          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.60it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.59it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     89/500     0.367G   0.009006          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.52it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 22.92it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     90/500     0.367G    0.01494          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.42it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 52.58it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     91/500     0.367G    0.01096          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.16it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.70it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     92/500     0.367G   0.007362          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.92it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.42it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     93/500     0.367G    0.01039          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.75it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.38it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     94/500     0.367G   0.007707          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.16it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.29it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     95/500     0.367G   0.008843          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.78it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.80it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     96/500     0.367G    0.01103          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.05it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.58it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


     97/500     0.367G    0.00723          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.96it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     98/500     0.367G   0.007836          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.17it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 20.24it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


     99/500     0.367G   0.005273          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.37it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    100/500     0.367G   0.007042          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.83it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.42it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    101/500     0.367G   0.004746          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 45.67it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    102/500     0.367G   0.005232          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.44it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    103/500     0.367G   0.006906          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.07it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.80it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    104/500     0.367G   0.006734          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.70it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.28it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    105/500     0.367G   0.004556          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.04it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.07it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    106/500     0.367G   0.004184          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.92it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    107/500     0.367G   0.004535          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.49it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.17it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    108/500     0.367G   0.004231          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.70it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.18it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    109/500     0.367G   0.003182          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.59it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.56it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    110/500     0.367G   0.004414          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.30it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.82it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    111/500     0.367G   0.003142          1        224: 100%|██████████| 23/23 [00:02<00:00, 10.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.91it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    112/500     0.367G    0.00297          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.40it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.90it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    113/500     0.367G   0.003348          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.83it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    114/500     0.367G   0.003134          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.97it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    115/500     0.367G   0.003974          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.98it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    116/500     0.367G   0.002484          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.85it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.80it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    117/500     0.367G   0.002855          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.76it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 23.97it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    118/500     0.367G   0.001954          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.37it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    119/500     0.367G   0.003071          1        224: 100%|██████████| 23/23 [00:02<00:00, 10.93it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.65it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    120/500     0.367G   0.002343          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.18it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.08it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    121/500     0.367G   0.002404          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.99it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    122/500     0.367G   0.002172          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.70it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.39it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    123/500     0.367G   0.002338          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.67it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 23.86it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    124/500     0.367G   0.002225          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.36it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.82it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    125/500     0.367G   0.003252          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.48it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    126/500     0.367G   0.001803          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.33it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    127/500     0.367G   0.001607          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.21it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.39it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    128/500     0.367G   0.001703          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.81it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.51it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    129/500     0.367G   0.002641          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.35it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.77it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    130/500     0.367G   0.002545          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.03it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    131/500     0.367G   0.002316          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.27it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.84it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    132/500     0.367G   0.001542          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.46it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.14it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    133/500     0.367G   0.001724          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.00it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.53it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    134/500     0.367G   0.001899          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.77it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.97it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    135/500     0.367G   0.001615          1        224: 100%|██████████| 23/23 [00:01<00:00, 15.06it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.02it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    136/500     0.367G   0.001444          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.89it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 46.75it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    137/500     0.367G   0.001366          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.08it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.08it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    138/500     0.367G   0.001757          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.53it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.57it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    139/500     0.367G   0.001625          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.82it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.89it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    140/500     0.367G   0.001471          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.04it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.44it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    141/500     0.367G   0.001356          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.75it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.06it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    142/500     0.367G   0.001402          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.21it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.33it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    143/500     0.367G   0.001674          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.37it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.67it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    144/500     0.367G   0.001712          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.87it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 45.02it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    145/500     0.367G   0.001401          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.61it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 45.38it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    146/500     0.367G   0.001659          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.98it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.56it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    147/500     0.367G   0.001592          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.66it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.28it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    148/500     0.367G   0.001371          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.71it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.96it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    149/500     0.367G   0.001167          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.85it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.79it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    150/500     0.367G   0.001411          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.70it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.64it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    151/500     0.367G   0.001085          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.49it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.07it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    152/500     0.367G   0.001243          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.29it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    153/500     0.367G   0.001056          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.53it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.10it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    154/500     0.367G   0.001583          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.07it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.17it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    155/500     0.367G   0.001624          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.10it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.22it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    156/500     0.367G   0.001322          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.64it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.58it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    157/500     0.367G   0.001242          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.31it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.60it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    158/500     0.367G   0.001211          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.53it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.34it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    159/500     0.367G   0.001391          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.38it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 48.60it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    160/500     0.367G   0.001606          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.72it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.30it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    161/500     0.367G   0.001095          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.46it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.58it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    162/500     0.367G   0.001043          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.40it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.90it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    163/500     0.367G   0.001171          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.68it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.26it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    164/500     0.367G   0.001194          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.61it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.21it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    165/500     0.367G   0.001139          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.67it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.90it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    166/500     0.367G   0.001383          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.28it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.19it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    167/500     0.367G   0.001055          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.73it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    168/500     0.367G   0.001053          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.72it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.81it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    169/500     0.367G   0.001325          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.03it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.92it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    170/500     0.367G   0.001392          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.18it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.07it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    171/500     0.367G  0.0008682          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.92it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    172/500     0.367G    0.00112          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.43it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.75it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    173/500     0.367G  0.0008429          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.51it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.41it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    174/500     0.367G  0.0009305          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.33it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.65it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    175/500     0.367G  0.0009151          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.26it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.40it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    176/500     0.367G  0.0008219          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.21it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.61it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    177/500     0.367G   0.001074          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.15it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.22it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    178/500     0.367G  0.0009544          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.76it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    179/500     0.367G  0.0009462          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.38it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    180/500     0.367G  0.0009915          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.43it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.25it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    181/500     0.367G   0.001078          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.22it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.69it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    182/500     0.367G  0.0008797          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.68it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.61it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    183/500     0.367G  0.0009131          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.72it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.06it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    184/500     0.367G  0.0009512          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.28it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.51it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    185/500     0.367G   0.001007          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.87it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    186/500     0.367G  0.0008331          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.94it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.81it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    187/500     0.367G  0.0007659          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.36it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.53it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    188/500     0.367G  0.0007676          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.46it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    189/500     0.367G  0.0007924          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.51it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.69it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    190/500     0.367G  0.0009724          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.35it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 45.26it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    191/500     0.367G  0.0007012          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.53it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 46.04it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    192/500     0.367G   0.001035          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.71it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.29it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    193/500     0.367G  0.0009357          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.54it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 21.53it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    194/500     0.367G  0.0007697          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.15it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 53.83it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    195/500     0.367G   0.001093          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.45it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.32it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    196/500     0.367G   0.001973          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.92it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.15it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    197/500     0.367G  0.0009118          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.87it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.06it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    198/500     0.367G   0.000759          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.60it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.72it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    199/500     0.367G  0.0008578          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.39it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    200/500     0.367G  0.0008679          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.30it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.51it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    201/500     0.367G  0.0007878          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.77it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.98it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    202/500     0.367G  0.0007908          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.42it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.56it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    203/500     0.367G  0.0006938          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.89it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.75it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    204/500     0.367G   0.000774          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.13it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.44it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    205/500     0.367G  0.0007198          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.06it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.87it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    206/500     0.367G  0.0008063          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.65it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.87it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    207/500     0.367G   0.000997          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.64it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.34it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    208/500     0.367G  0.0007861          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.07it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.08it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    209/500     0.367G  0.0009505          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.85it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.84it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    210/500     0.367G  0.0006896          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.04it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.83it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    211/500     0.367G  0.0007686          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.05it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 46.13it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    212/500     0.367G  0.0005738          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.64it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    213/500     0.367G   0.000743          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.62it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    214/500     0.367G  0.0008003          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.37it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    215/500     0.367G  0.0007329          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.33it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.08it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    216/500     0.367G  0.0006297          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.59it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    217/500     0.367G  0.0008288          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.13it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    218/500     0.367G   0.000649          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.65it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.77it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    219/500     0.367G  0.0006499          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.07it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    220/500     0.367G   0.001074          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.17it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    221/500     0.367G  0.0007502          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.08it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.16it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    222/500     0.367G  0.0006776          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.43it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.77it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    223/500     0.367G  0.0007412          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.85it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.58it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    224/500     0.367G   0.000815          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.24it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.65it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    225/500     0.367G  0.0009473          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.98it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.63it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    226/500     0.367G  0.0006477          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.71it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.25it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    227/500     0.367G  0.0007924          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.48it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.51it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    228/500     0.367G  0.0007101          1        224: 100%|██████████| 23/23 [00:02<00:00, 10.35it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.88it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    229/500     0.367G  0.0006688          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.87it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 59.28it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    230/500     0.367G  0.0006685          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.71it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.83it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    231/500     0.367G   0.000826          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.73it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.31it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    232/500     0.367G  0.0008373          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.87it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.86it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    233/500     0.367G  0.0007955          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.40it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.07it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    234/500     0.367G  0.0006543          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.83it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.17it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    235/500     0.367G  0.0008053          1        224: 100%|██████████| 23/23 [00:01<00:00, 15.05it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.13it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    236/500     0.367G  0.0006758          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.63it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.82it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    237/500     0.367G   0.000737          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.35it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.24it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    238/500     0.367G  0.0007097          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.43it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    239/500     0.367G  0.0006019          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.83it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.95it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    240/500     0.367G  0.0006863          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.87it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.19it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    241/500     0.367G  0.0005391          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.90it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.94it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    242/500     0.367G  0.0007675          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.79it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.57it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    243/500     0.367G   0.000709          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.85it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.96it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    244/500     0.367G  0.0006138          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.16it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 21.64it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    245/500     0.367G  0.0007896          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.02it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    246/500     0.367G  0.0008682          1        224: 100%|██████████| 23/23 [00:01<00:00, 15.02it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 47.12it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    247/500     0.367G  0.0007342          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.76it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.63it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    248/500     0.367G  0.0007046          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.51it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.10it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    249/500     0.367G  0.0006155          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.42it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    250/500     0.367G  0.0007422          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.99it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    251/500     0.367G  0.0006049          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.55it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.89it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    252/500     0.367G  0.0006983          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.31it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.01it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    253/500     0.367G  0.0005838          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.39it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.09it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    254/500     0.367G  0.0007242          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.18it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 48.04it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    255/500     0.367G  0.0005047          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.36it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.14it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    256/500     0.367G  0.0007054          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 45.32it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    257/500     0.367G  0.0007768          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.86it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    258/500     0.367G  0.0006402          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 23.98it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    259/500     0.367G  0.0005824          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.04it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.66it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    260/500     0.367G  0.0006594          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.59it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.87it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    261/500     0.367G  0.0006279          1        224: 100%|██████████| 23/23 [00:01<00:00, 15.80it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.04it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    262/500     0.367G  0.0005587          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.31it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.69it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    263/500     0.367G  0.0006693          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.59it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.68it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    264/500     0.367G  0.0005209          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.46it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.80it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    265/500     0.367G   0.000718          1        224: 100%|██████████| 23/23 [00:01<00:00, 15.05it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.27it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    266/500     0.367G  0.0005539          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.53it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    267/500     0.367G  0.0005856          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.99it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 43.15it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    268/500     0.367G  0.0006358          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.43it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.02it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    269/500     0.367G  0.0006384          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.51it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.07it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    270/500     0.367G  0.0005419          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.39it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 45.08it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    271/500     0.367G  0.0007497          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.25it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.24it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    272/500     0.367G  0.0004982          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.72it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.00it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    273/500     0.367G  0.0006664          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.54it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.29it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    274/500     0.367G  0.0005481          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.19it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    275/500     0.367G  0.0005806          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.13it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    276/500     0.367G  0.0006265          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.32it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.57it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    277/500     0.367G  0.0007851          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.62it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.82it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    278/500     0.367G  0.0006988          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.61it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 43.14it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    279/500     0.367G  0.0004935          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.31it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.01it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    280/500     0.367G  0.0005434          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.65it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.14it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    281/500     0.367G  0.0009171          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.67it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.84it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    282/500     0.367G  0.0004611          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.45it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.21it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    283/500     0.367G  0.0005403          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.30it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.40it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    284/500     0.367G  0.0005813          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.81it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.21it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    285/500     0.367G  0.0005502          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.00it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.42it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    286/500     0.367G  0.0005292          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.21it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.68it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    287/500     0.367G  0.0005298          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.32it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    288/500     0.367G  0.0006862          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.78it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.17it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    289/500     0.367G  0.0006898          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.60it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.05it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    290/500     0.367G  0.0005935          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.62it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.61it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    291/500     0.367G  0.0005602          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.96it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.69it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    292/500     0.367G  0.0005791          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.77it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.80it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    293/500     0.367G  0.0005859          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.05it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    294/500     0.367G  0.0004777          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.62it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.31it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    295/500     0.367G  0.0005836          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.82it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.51it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    296/500     0.367G  0.0007487          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.75it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    297/500     0.367G   0.000525          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.02it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.78it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    298/500     0.367G  0.0006184          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.26it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    299/500     0.367G  0.0006424          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.62it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.50it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    300/500     0.367G  0.0007881          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.74it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.12it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    301/500     0.367G  0.0005859          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.08it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.69it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    302/500     0.367G  0.0005823          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.80it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 47.61it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    303/500     0.367G  0.0008008          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.89it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.48it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    304/500     0.367G  0.0005932          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 43.66it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    305/500     0.367G  0.0005926          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.99it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.31it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    306/500     0.367G  0.0005559          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.25it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.35it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    307/500     0.367G  0.0005635          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.30it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.76it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    308/500     0.367G   0.000463          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.41it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.45it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    309/500     0.367G  0.0007912          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.11it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.31it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    310/500     0.367G  0.0005344          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.09it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.17it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    311/500     0.367G  0.0005674          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.98it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    312/500     0.367G  0.0006725          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.67it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.09it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    313/500     0.367G  0.0006235          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.67it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 43.08it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    314/500     0.367G  0.0006734          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.29it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.34it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    315/500     0.367G  0.0005216          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.52it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.21it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    316/500     0.367G  0.0005851          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.99it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 43.25it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    317/500     0.367G  0.0004968          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.59it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.24it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    318/500     0.367G  0.0005454          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.00it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.52it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    319/500     0.367G  0.0005092          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.02it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.37it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    320/500     0.367G  0.0007319          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.36it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.09it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    321/500     0.367G  0.0005728          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.50it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    322/500     0.367G  0.0005781          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.82it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.25it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    323/500     0.367G  0.0006798          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.32it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.42it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    324/500     0.367G  0.0005963          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.38it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.24it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    325/500     0.367G   0.000479          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.10it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.53it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    326/500     0.367G  0.0005786          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.47it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.55it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    327/500     0.367G  0.0005662          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.84it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.34it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    328/500     0.367G   0.000508          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.85it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.12it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    329/500     0.367G  0.0005453          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.38it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.77it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    330/500     0.367G  0.0005882          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.68it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.97it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    331/500     0.367G  0.0005207          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.16it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.68it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    332/500     0.367G  0.0004659          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.61it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.28it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    333/500     0.367G  0.0004869          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.36it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.54it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    334/500     0.367G  0.0005195          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.56it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    335/500     0.367G  0.0004693          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.65it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 54.22it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    336/500     0.367G  0.0005452          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.75it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    337/500     0.367G  0.0005886          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.33it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.16it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    338/500     0.367G  0.0006817          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.12it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    339/500     0.367G  0.0005089          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.20it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 29.98it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    340/500     0.367G  0.0006427          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.94it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.79it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    341/500     0.367G  0.0005821          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.27it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.85it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    342/500     0.367G  0.0005663          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.98it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.75it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    343/500     0.367G   0.000572          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.15it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 45.50it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    344/500     0.367G  0.0006345          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.25it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 43.29it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    345/500     0.367G  0.0005656          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.31it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.94it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    346/500     0.367G  0.0004967          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.93it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.85it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    347/500     0.367G  0.0005814          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.63it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.38it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    348/500     0.367G   0.001048          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.87it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.63it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    349/500     0.367G  0.0005678          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.05it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    350/500     0.367G  0.0004344          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.15it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.77it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    351/500     0.367G  0.0005661          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.71it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.36it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    352/500     0.367G  0.0005903          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.78it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.75it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    353/500     0.367G  0.0005229          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.26it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.76it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    354/500     0.367G  0.0005514          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.65it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    355/500     0.367G   0.000702          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.37it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.50it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    356/500     0.367G  0.0004813          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.97it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.30it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    357/500     0.367G  0.0006932          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.94it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.46it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    358/500     0.367G  0.0005241          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.53it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    359/500     0.367G  0.0006042          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.57it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.99it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    360/500     0.367G  0.0005103          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.47it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.41it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    361/500     0.367G  0.0007888          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.63it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.82it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    362/500     0.367G  0.0006211          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.11it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.20it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    363/500     0.367G  0.0004869          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.66it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.46it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    364/500     0.367G  0.0005251          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.27it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.19it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    365/500     0.367G  0.0004539          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.75it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.59it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    366/500     0.367G  0.0005061          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.45it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 55.42it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    367/500     0.367G  0.0005575          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.19it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 46.13it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    368/500     0.367G  0.0004386          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.79it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    369/500     0.367G  0.0004841          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.98it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    370/500     0.367G  0.0005382          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.30it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    371/500     0.367G  0.0004285          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.79it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    372/500     0.367G  0.0006179          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.72it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 46.43it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    373/500     0.367G  0.0004909          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.46it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 29.76it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    374/500     0.367G  0.0005426          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.28it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 43.83it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    375/500     0.367G  0.0006302          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.68it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.25it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    376/500     0.367G  0.0006131          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.63it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.09it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    377/500     0.367G  0.0005019          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.73it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 45.34it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    378/500     0.367G  0.0005334          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.80it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.17it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    379/500     0.367G   0.000479          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.84it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.41it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    380/500     0.367G   0.000671          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.34it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    381/500     0.367G  0.0006464          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.19it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.47it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    382/500     0.367G  0.0004541          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.27it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.19it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    383/500     0.367G  0.0004714          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.44it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.09it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    384/500     0.367G  0.0005924          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.47it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.06it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    385/500     0.367G  0.0005158          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.81it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 46.69it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    386/500     0.367G  0.0006039          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.06it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.27it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    387/500     0.367G  0.0005282          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.49it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.41it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    388/500     0.367G  0.0004605          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.75it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.23it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    389/500     0.367G  0.0003741          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.40it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.54it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    390/500     0.367G  0.0005106          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.53it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.18it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    391/500     0.367G  0.0004924          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.74it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.91it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    392/500     0.367G  0.0004025          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.31it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.80it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    393/500     0.367G  0.0004008          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.90it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.44it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    394/500     0.367G  0.0004594          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.59it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.97it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    395/500     0.367G  0.0005283          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.15it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.74it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    396/500     0.367G  0.0005244          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.87it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.30it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    397/500     0.367G  0.0004706          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.08it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    398/500     0.367G  0.0004455          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.51it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 47.36it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    399/500     0.367G   0.000488          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.52it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.23it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    400/500     0.367G  0.0004841          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.98it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.45it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    401/500     0.367G  0.0005476          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.83it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.28it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    402/500     0.367G   0.000534          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.79it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    403/500     0.367G  0.0005225          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.54it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.17it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    404/500     0.367G  0.0005879          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.76it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 46.64it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    405/500     0.367G  0.0003974          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.24it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.30it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    406/500     0.367G  0.0006444          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.83it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.85it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    407/500     0.367G  0.0005452          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 50.53it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    408/500     0.367G   0.000468          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.13it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.24it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    409/500     0.367G  0.0005634          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 46.60it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    410/500     0.367G  0.0004309          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.17it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 51.92it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    411/500     0.367G  0.0006552          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.52it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.28it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    412/500     0.367G  0.0006432          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.83it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.37it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    413/500     0.367G  0.0005908          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.17it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.71it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    414/500     0.367G  0.0006486          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.28it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.18it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    415/500     0.367G  0.0005299          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.29it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.68it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    416/500     0.367G  0.0004056          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.39it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.68it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    417/500     0.367G  0.0006088          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.60it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.45it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    418/500     0.367G  0.0005731          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.39it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 49.43it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    419/500     0.367G  0.0004884          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.56it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    420/500     0.367G  0.0005314          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.23it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.33it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    421/500     0.367G  0.0005094          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.81it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.37it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    422/500     0.367G   0.000461          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.69it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    423/500     0.367G  0.0004828          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.93it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.93it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    424/500     0.367G  0.0006086          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.36it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.46it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    425/500     0.367G  0.0004995          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.15it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.82it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    426/500     0.367G  0.0006702          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.62it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.29it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    427/500     0.367G  0.0004459          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.83it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.11it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    428/500     0.367G  0.0004339          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.37it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.50it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    429/500     0.367G  0.0005399          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.25it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.37it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    430/500     0.367G  0.0003674          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.20it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.53it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    431/500     0.367G  0.0003805          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.57it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 46.58it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    432/500     0.367G  0.0003919          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.67it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.95it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    433/500     0.367G  0.0005073          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.71it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    434/500     0.367G  0.0004362          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.47it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 49.77it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    435/500     0.367G  0.0007665          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.12it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    436/500     0.367G   0.000469          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.26it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 45.62it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    437/500     0.367G  0.0005096          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.85it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.85it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    438/500     0.367G  0.0004277          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.38it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 49.73it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    439/500     0.367G  0.0004701          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.09it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.08it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    440/500     0.367G   0.000463          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.31it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.51it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    441/500     0.367G  0.0004571          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.38it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.37it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    442/500     0.367G  0.0003994          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.78it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.04it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    443/500     0.367G   0.000467          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.29it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 22.99it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    444/500     0.367G  0.0004877          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.60it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.27it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    445/500     0.367G  0.0005538          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.33it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.34it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    446/500     0.367G  0.0005388          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.41it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 47.52it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    447/500     0.367G  0.0003746          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.61it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    448/500     0.367G  0.0005233          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.22it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.03it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    449/500     0.367G  0.0005581          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.59it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    450/500     0.367G  0.0005052          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.10it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 51.90it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    451/500     0.367G  0.0003408          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.15it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.63it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    452/500     0.367G  0.0005579          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.37it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.64it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    453/500     0.367G  0.0005298          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.10it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.02it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    454/500     0.367G  0.0003993          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.79it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    455/500     0.367G  0.0004688          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.12it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    456/500     0.367G  0.0004827          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.21it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 47.81it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    457/500     0.367G  0.0006336          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.49it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.44it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    458/500     0.367G  0.0006288          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.39it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.62it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    459/500     0.367G  0.0003708          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.25it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.10it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    460/500     0.367G  0.0004244          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.46it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.29it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    461/500     0.367G  0.0004317          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.39it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.33it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    462/500     0.367G  0.0005378          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.92it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    463/500     0.367G  0.0004246          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.74it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 43.95it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    464/500     0.367G  0.0004989          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 45.53it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    465/500     0.367G  0.0005758          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.17it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.93it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    466/500     0.367G  0.0009648          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.48it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 54.01it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    467/500     0.367G    0.00059          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.26it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    468/500     0.367G  0.0005161          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.84it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.91it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    469/500     0.367G  0.0004818          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.76it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.17it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    470/500     0.367G  0.0004485          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.09it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.24it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    471/500     0.367G  0.0004077          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.18it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 46.18it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    472/500     0.367G  0.0004405          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.50it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    473/500     0.367G  0.0004941          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.51it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    474/500     0.367G  0.0004685          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.66it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.80it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    475/500     0.367G  0.0005433          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.23it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.87it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    476/500     0.367G  0.0004259          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.73it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.61it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    477/500     0.367G  0.0004587          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.28it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.78it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    478/500     0.367G  0.0005745          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.68it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.78it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    479/500     0.367G  0.0003919          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.16it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 43.35it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    480/500     0.367G  0.0004507          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.06it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.78it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    481/500     0.367G  0.0004508          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.20it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.14it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    482/500     0.367G  0.0004664          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.07it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    483/500     0.367G  0.0004707          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.57it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.83it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    484/500     0.367G  0.0005133          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.61it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.15it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    485/500     0.367G  0.0004545          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.06it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.42it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    486/500     0.367G   0.000367          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.33it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.65it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    487/500     0.367G  0.0005553          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.68it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 46.93it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    488/500     0.367G   0.000464          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.80it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.41it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    489/500     0.367G  0.0006197          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.73it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.98it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    490/500     0.367G  0.0005002          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.64it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.85it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    491/500     0.367G  0.0004663          1        224: 100%|██████████| 23/23 [00:02<00:00,  9.08it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 22.57it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    492/500     0.367G  0.0004008          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.67it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    493/500     0.367G  0.0003902          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.54it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.26it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    494/500     0.367G  0.0005737          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.98it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    495/500     0.367G  0.0004874          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.24it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.52it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    496/500     0.367G  0.0004499          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.31it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.63it/s]


                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size


    497/500     0.367G  0.0003982          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.87it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 29.81it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    498/500     0.367G  0.0003971          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.20it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.39it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    499/500     0.367G  0.0006355          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.92it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.36it/s]

                   all          1          1



      Epoch    GPU_mem       loss  Instances       Size


    500/500     0.367G  0.0004842          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.08it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.59it/s]

                   all          1          1



500 epochs completed in 0.393 hours.
Optimizer stripped from runs/classify/train/weights/last.pt, 3.0MB
Optimizer stripped from runs/classify/train/weights/best.pt, 3.0MB

Validating runs/classify/train/weights/best.pt...
Ultralytics YOLOv8.2.6 🚀 Python-3.8.10 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2070 SUPER, 8192MiB)
YOLOv8n-cls summary (fused): 73 layers, 1438723 parameters, 0 gradients, 3.3 GFLOPs
train: /root/aifr/bottle-classification-YOLOv8/data/train... found 23 images in 3 classes ✅ 
val: /root/aifr/bottle-classification-YOLOv8/data/val... found 6 images in 3 classes ✅ 
test: None...


               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 65.01it/s]


                   all          1          1
Speed: 0.9ms preprocess, 4.4ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to runs/classify/train
Results saved to runs/classify/train


Ultralytics YOLOv8.2.6 🚀 Python-3.8.10 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2070 SUPER, 8192MiB)
engine/trainer: task=classify, mode=train, model=yolov8n-cls.pt, data=/root/aifr/bottle-classification-YOLOv8/data, epochs=500, time=None, patience=100, batch=1, imgsz=224, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/classify/train
train: /root/aifr/bottle-classification-YOLOv8/data/train... found 23 images in 3 classes ✅ 
val: /root/aifr/bottle-classification-YOLOv8/data/val... found 6 images in 3 classes ✅ 
test: None...
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning /root/aifr/bottle-classification-YOLOv8/data/train... 23 images, 0 corrupt: 100%|██████████| 23/23 [00:00<?, ?it/s]
val: Scanning /root/aifr/bottle-classification-YOLOv8/data/val... 6 images, 0 corrupt: 100%|██████████| 6/6 [00:00<?, ?it/s]
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 8 dataloader workers
Logging results to runs/classify/train
Starting training for 500 epochs...

      Epoch    GPU_mem       loss  Instances       Size
      1/500     0.508G      1.113          1        224: 100%|██████████| 23/23 [00:03<00:00,  5.78it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.91it/s]
                   all      0.333          1


      Epoch    GPU_mem       loss  Instances       Size
      2/500     0.367G      1.075          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.66it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.73it/s]
                   all      0.333          1


      Epoch    GPU_mem       loss  Instances       Size
      3/500     0.367G      1.099          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.15it/s]
                   all      0.833          1


      Epoch    GPU_mem       loss  Instances       Size
      4/500     0.367G      1.038          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.05it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.17it/s]
                   all      0.833          1

      Epoch    GPU_mem       loss  Instances       Size
      5/500     0.367G      1.063          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.13it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.48it/s]
                   all      0.833          1


      Epoch    GPU_mem       loss  Instances       Size
      6/500     0.367G      1.056          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.06it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.20it/s]
                   all        0.5          1


      Epoch    GPU_mem       loss  Instances       Size
      7/500     0.367G      1.002          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.52it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.75it/s]
                   all        0.5          1


      Epoch    GPU_mem       loss  Instances       Size
      8/500     0.367G      1.028          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.87it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.42it/s]
                   all        0.5          1


      Epoch    GPU_mem       loss  Instances       Size
      9/500     0.367G      1.012          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.00it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.75it/s]
                   all        0.5          1


      Epoch    GPU_mem       loss  Instances       Size
     10/500     0.367G      1.001          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 21.83it/s]
                   all        0.5          1

      Epoch    GPU_mem       loss  Instances       Size
     11/500     0.367G     0.9829          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.43it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 22.06it/s]
                   all      0.667          1


      Epoch    GPU_mem       loss  Instances       Size
     12/500     0.367G     0.9588          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.36it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 41.40it/s]
                   all      0.667          1


      Epoch    GPU_mem       loss  Instances       Size
     13/500     0.367G     0.9242          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.65it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.79it/s]
                   all      0.667          1


      Epoch    GPU_mem       loss  Instances       Size
     14/500     0.367G     0.9498          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.17it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.80it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
     15/500     0.367G      0.896          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.93it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.20it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     16/500     0.367G     0.8936          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.49it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.72it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     17/500     0.367G     0.8579          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.08it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.34it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     18/500     0.367G     0.8378          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.68it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.90it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     19/500     0.367G     0.8179          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.74it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 48.19it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     20/500     0.367G     0.8434          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.90it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     21/500     0.367G     0.7937          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.10it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.49it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     22/500     0.367G     0.7596          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.79it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.00it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     23/500     0.367G     0.7682          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.64it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.98it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     24/500     0.367G     0.7758          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.51it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.50it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     25/500     0.367G     0.7715          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.47it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.79it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     26/500     0.367G     0.7246          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.82it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
     27/500     0.367G     0.7571          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.47it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.47it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     28/500     0.367G     0.7554          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.87it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.48it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     29/500     0.367G     0.6575          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.66it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     30/500     0.367G        0.7          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.92it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.47it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     31/500     0.367G      0.642          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.71it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     32/500     0.367G       0.57          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.04it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.89it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
     33/500     0.367G      0.614          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.42it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 21.50it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     34/500     0.367G     0.6275          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.62it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.49it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     35/500     0.367G     0.5776          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.83it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.02it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     36/500     0.367G     0.5319          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 44.16it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     37/500     0.367G     0.5038          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.83it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.71it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     38/500     0.367G     0.5369          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.27it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.21it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     39/500     0.367G     0.4876          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.42it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.88it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
     40/500     0.367G      0.494          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.81it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.81it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
     41/500     0.367G     0.5107          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.40it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.42it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     42/500     0.367G     0.4086          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.67it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     43/500     0.367G     0.3876          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.99it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.66it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     44/500     0.367G     0.4578          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.63it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.24it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     45/500     0.367G     0.3734          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.80it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.68it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     46/500     0.367G     0.3053          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.26it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.73it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
     47/500     0.367G     0.3264          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.96it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 23.87it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     48/500     0.367G     0.2812          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.59it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.57it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     49/500     0.367G     0.3134          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.66it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.51it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     50/500     0.367G      0.264          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.44it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.26it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     51/500     0.367G     0.2816          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.61it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.09it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     52/500     0.367G     0.2259          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.02it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.90it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     53/500     0.367G     0.2695          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.93it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.47it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     54/500     0.367G     0.1806          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.43it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.20it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     55/500     0.367G      0.194          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.22it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.07it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     56/500     0.367G     0.1791          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.41it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     57/500     0.367G     0.1581          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.70it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.68it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     58/500     0.367G     0.1787          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.77it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     59/500     0.367G     0.1424          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.53it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 29.05it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     60/500     0.367G     0.1061          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.27it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.42it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     61/500     0.367G     0.1215          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.45it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.04it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     62/500     0.367G     0.1248          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.72it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     63/500     0.367G       0.11          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.93it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     64/500     0.367G     0.1071          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.14it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     65/500     0.367G    0.08744          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.59it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 27.82it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     66/500     0.367G    0.07723          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.19it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.33it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     67/500     0.367G    0.07291          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.59it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.35it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     68/500     0.367G    0.06923          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.39it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     69/500     0.367G    0.05293          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.33it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.88it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     70/500     0.367G    0.07854          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.99it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 18.94it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     71/500     0.367G    0.05136          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.80it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.15it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     72/500     0.367G    0.05217          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 43.04it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     73/500     0.367G    0.03822          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.18it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.46it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     74/500     0.367G    0.04644          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.92it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     75/500     0.367G    0.04849          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.99it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.34it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     76/500     0.367G     0.0481          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.68it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.18it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     77/500     0.367G    0.04004          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.26it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.06it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     78/500     0.367G    0.05096          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.79it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.76it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     79/500     0.367G    0.02321          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.16it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
     80/500     0.367G    0.02042          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.19it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     81/500     0.367G    0.02943          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 39.49it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     82/500     0.367G    0.02314          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.73it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 24.71it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     83/500     0.367G    0.01666          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.47it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 19.39it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     84/500     0.367G    0.01778          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.57it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.51it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
     85/500     0.367G    0.01856          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.80it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.70it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     86/500     0.367G    0.01602          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.40it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.56it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     87/500     0.367G    0.01296          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.95it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.69it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     88/500     0.367G     0.0135          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.60it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.59it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     89/500     0.367G   0.009006          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.52it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 22.92it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     90/500     0.367G    0.01494          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.42it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 52.58it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     91/500     0.367G    0.01096          1        224: 100%|██████████| 23/23 [00:01<00:00, 14.16it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.70it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     92/500     0.367G   0.007362          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.92it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.42it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     93/500     0.367G    0.01039          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.75it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.38it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     94/500     0.367G   0.007707          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.16it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.29it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     95/500     0.367G   0.008843          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.78it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.80it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     96/500     0.367G    0.01103          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.05it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.58it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
     97/500     0.367G    0.00723          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.96it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     98/500     0.367G   0.007836          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.17it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 20.24it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
     99/500     0.367G   0.005273          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.37it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    100/500     0.367G   0.007042          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.83it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.42it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    101/500     0.367G   0.004746          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 45.67it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    102/500     0.367G   0.005232          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.44it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    103/500     0.367G   0.006906          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.07it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.80it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    104/500     0.367G   0.006734          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.70it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.28it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    105/500     0.367G   0.004556          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.04it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.07it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    106/500     0.367G   0.004184          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.92it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    107/500     0.367G   0.004535          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.49it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.17it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    108/500     0.367G   0.004231          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.70it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.18it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    109/500     0.367G   0.003182          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.59it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 25.56it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    110/500     0.367G   0.004414          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.30it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 37.82it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    111/500     0.367G   0.003142          1        224: 100%|██████████| 23/23 [00:02<00:00, 10.69it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.91it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    112/500     0.367G    0.00297          1        224: 100%|██████████| 23/23 [00:02<00:00, 11.40it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.90it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    113/500     0.367G   0.003348          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 35.83it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    114/500     0.367G   0.003134          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.97it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
    115/500     0.367G   0.003974          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.58it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 36.98it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
    116/500     0.367G   0.002484          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.85it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.80it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
    117/500     0.367G   0.002855          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.76it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 23.97it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    118/500     0.367G   0.001954          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.56it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.37it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    119/500     0.367G   0.003071          1        224: 100%|██████████| 23/23 [00:02<00:00, 10.93it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 26.65it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    120/500     0.367G   0.002343          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.18it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.08it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    121/500     0.367G   0.002404          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 30.99it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
    122/500     0.367G   0.002172          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.70it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.39it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    123/500     0.367G   0.002338          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.67it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 23.86it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    124/500     0.367G   0.002225          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.36it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 32.82it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    125/500     0.367G   0.003252          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.88it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.48it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    126/500     0.367G   0.001803          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 40.33it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    127/500     0.367G   0.001607          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.21it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 31.39it/s]
                   all          1          1

      Epoch    GPU_mem       loss  Instances       Size
    128/500     0.367G   0.001703          1        224: 100%|██████████| 23/23 [00:01<00:00, 11.81it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 34.51it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    129/500     0.367G   0.002641          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.35it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 28.77it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    130/500     0.367G   0.002545          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.50it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.03it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    131/500     0.367G   0.002316          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.27it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 42.84it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    132/500     0.367G   0.001542          1        224: 100%|██████████| 23/23 [00:01<00:00, 12.46it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 33.14it/s]
                   all          1          1


      Epoch    GPU_mem       loss  Instances       Size
    133/500     0.367G   0.001724          1        224: 100%|██████████| 23/23 [00:01<00:00, 13.00it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 3/3 [00:00<00:00, 38.53it/s]